pub const DEFAULT_RENDER_LAYER: usize = 0;
pub const VIEW_MODEL_RENDER_LAYER: usize = 1;

pub const WORLD_COLLISION_LAYER: u32 = 0b0001;
pub const PLAYER_HITBOX_LAYER: u32 = 0b0010;
pub const WORLD_BOUNDARY_COLLISION_LAYER: u32 = 0b0100;
pub const SOLID_WORLD_COLLISION_LAYERS: u32 = WORLD_COLLISION_LAYER | WORLD_BOUNDARY_COLLISION_LAYER;
pub const BULLET_QUERY_LAYERS: u32 = SOLID_WORLD_COLLISION_LAYERS | PLAYER_HITBOX_LAYER;
pub const PLAYER_MOVEMENT_COLLISION_LAYERS: u32 = SOLID_WORLD_COLLISION_LAYERS | PLAYER_HITBOX_LAYER;

pub const WORLD_SIZE: f32 = 72.0;
pub const WORLD_HALF: f32 = WORLD_SIZE * 0.5;

pub const GHOST_MODEL_SCALE: f32 = 0.01;
pub const GHOST_MODEL_MIN_Y: f32 = -23.0134;
pub const GHOST_MODEL_MIN_Z: f32 = 1.0306;
pub const GHOST_MODEL_MAX_Z: f32 = 35.9537;
pub const GHOST_MODEL_CENTER_Z: f32 = (GHOST_MODEL_MIN_Z + GHOST_MODEL_MAX_Z) * 0.5;
pub const GHOST_MODEL_EYE_HEIGHT: f32 = 30.79;
pub const GHOST_MODEL_EYE_Y: f32 = GHOST_MODEL_MIN_Y + GHOST_MODEL_EYE_HEIGHT;
pub const GHOST_MODEL_EYE_OFFSET_Y: f32 = -GHOST_MODEL_EYE_Y * GHOST_MODEL_SCALE;
pub const GHOST_MODEL_CENTER_OFFSET_Z: f32 = GHOST_MODEL_CENTER_Z * GHOST_MODEL_SCALE;

pub const STAND_EYE_HEIGHT: f32 = 0.4;
pub const CROUCH_EYE_HEIGHT: f32 = GHOST_MODEL_EYE_HEIGHT * GHOST_MODEL_SCALE;
pub const CROUCH_TRANSITION_SPEED: f32 = 12.0;
pub const CROUCH_SPEED_MULTIPLIER: f32 = 0.55;
pub const MOVE_SPEED: f32 = 8.0 / 3.0;
pub const JUMP_SPEED: f32 = 4.2;
pub const PLAYER_GRAVITY: f32 = 18.0;

pub const MAX_DASH_CHARGES: u8 = 3;
pub const DASH_AMOUNT: f32 = 36.0;
pub const DASH_VELOCITY_DAMPING: f32 = 12.0;
pub const DASH_STOP_SPEED: f32 = 0.25;
pub const DASH_RECHARGE_SECONDS: f32 = 6.0;

pub const BULLET_SPEED: f32 = 15.0;
pub const BULLET_LIFETIME: f32 = 1.8;
pub const BULLET_RADIUS: f32 = 0.03;
pub const BULLET_DROP_GRAVITY: f32 = 6.0;

pub const TERRAIN_HEIGHT: f32 = 0.0;
